#!/bin/bash

INTERFACE=$(networksetup -listallhardwareports | awk '$3=="Wi-Fi" {getline; print $2}')

function toggle_wifi {
	networksetup -setairportpower $INTERFACE $1;
}

if [ $# -eq 0 ]; then
	toggle_wifi off;
	echo "Wi-Fi reset.";
	sleep 1;
	toggle_wifi on;
fi
case "$1" in
-off) toggle_wifi off;
	echo "Wi-Fi off";
	exit;
;;
-on) toggle_wifi on;
	echo "Wi-Fi on";
	exit;
;;
esac